Support getters in the object inspector
RecordReplay/devtools pull request #5555
Opened 2022-03-01 15:03 UTC by hbenl

Needs #5459 to be merged first.

2022-03-02 15:14 UTC, jaril commented
Fix #5461.

2022-03-02 19:07 UTC, abstractalgo requested changes
Again, I'm terrified by `forceUpdate()`'s sent as props through the components tree because we mutate data directly. I really wish there were a better way. 😕 

I can also recommend renaming the files in `object-inspector/utils` to reflect the actual objects that they represent (e.g. `getter.tsx` → `GetterItem.tsx` etc).

Let's also expand the tests to include getters.

As a test, I tried recording and replaying this example:
```js
class GetterTester {
  get time() {
    return "now is: " + (new Date()).toUTCString()
  }
}
const gt = new GetterTester()
console.log(gt)
```

...but got only this as an output:

<img width="183" alt="image" src="https://user-images.githubusercontent.com/1355455/156430692-d95d25f4-3d6f-4bca-9a53-142a53c409c2.png">

...which doesn't seem quite right.

2022-03-03 12:37 UTC, abstractalgo commented
> Did you perhaps accidentally view it on app.replay.io?

Hmm, it works now. Really not sure what went wrong yesterday (I recall being cautious about testing on the right version of the code), so maybe just didn't properly reload or something. Anyway...disregard that comment then. 😄

2022-03-03 12:52 UTC, hbenl commented on src/devtools/client/debugger/src/components/Editor/Preview/Popup.js
> +          roots={() => root.getChildren()}
Yes, if a node's label and value should be rerendered (without its focused and expanded state having changed, which also triggers rerendering), the `shouldItemUpdate(prevItem, nextItem)` function needs to be able to detect something has changed, so it needs a new item to be created for that node.
If we pass the root items directly, they will never be recreated and hence their labels and values are only rerendered when their focused/expanded state changes. That's OK for ValueItems and ContainerItems but GetterItems need to be rerendered when their values are loaded.

2022-03-03 13:21 UTC, hbenl commented on src/devtools/packages/devtools-reps/object-inspector/utils/index.ts
> +      await currentValue.loadIfNecessary();
Excellent. This could be useful in general, so I made it a method on ValueFront. Unfortunately I had to define 2 versions of it (sync and async).

2022-03-03 13:25 UTC, hbenl commented
> Again, I'm terrified by forceUpdate()'s sent as props through the components tree because we mutate data directly. I really wish there were a better way. :confused:

Yes, but I can't think of any (without another big refactor). Both the tree implementation that we're using here and our *Front classes don't seem to be suited for this.

2022-03-03 13:35 UTC, abstractalgo approved these changes
Small nit: comments say "...walks down this object's prototype chain", but it's actually "up the chain".

Otherwise, looks good. 👍

2022-03-03 14:52 UTC, hbenl commented
> comments say "...walks down this object's prototype chain", but it's actually "up the chain".

I've seen both and wanted to be consistent with `maxDepth`.

2022-03-03 14:52 UTC, merged